# Generated by Django 6.0.1 on 2026-02-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pinned', '-created_at']},
        ),
    ]
