# Generated by Django 6.0.1 on 2026-02-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_options_remove_note_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pinned', '-updated']},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
